### ISSUE TITLE
Unsure how to use this to interact with my extension

### ISSUE THREAD

**Issue by rafistrauss** [ejoubaud/cypress-browser-extension-plugin#1]
Hey @ejoubaud really excited to use the plugin. I'm just not clear on how exactly to use this to interact with my extension.

E.g. I've got a browser action that opens a popup when clicked and populates the popup with some info, based on the current page. How would I tell Cypress/CBEP to click the browser action, then check the content of the popup?

Much appreciated

**Comment by ejoubaud** [comment]
Hi @rafistrauss, tbh it's not a use-case I had in mind, I was rather focused on contentscript testing and controlling/resetting local storage. I'm not even sure what you're after would be doable with Cypress, I doubt in-page JS can access the browser's menus. Might be worth asking the Cypress team though, maybe they'll be able to suggest a way. But sadly I don't think this extension can help.
